version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run serve
    ports:
      - "8080:8080"
# docker-compose up --build

