version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    #ports:
     # - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    # uvicorn en mode reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # un Dockerfile léger pour le dev
    # lance le serveur Vue en mode dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules         # préserve les node_modules installés
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
