version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env               # contient POSTGRES_*
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile     # Dockerfile “prod”
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile     # Dockerfile “prod”
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
